/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import javax.swing.JOptionPane;
import progra.parqueo.*;

public class VentanaFactura extends javax.swing.JFrame {
    private static VentanaFactura VentanaFact;
    
    /**
     * Creates new form VentanaFactura
     */
    public VentanaFactura() {
        
        
        /*
        lblTitulo.setText(Parqueo.getInstance().getFactura().getTitulo());
        lblCedulaJuridica.setText(Parqueo.getInstance().getFactura().getCedulaJuridicaCompleto());
        lblDireccion.setText(Parqueo.getInstance().getFactura().getDireccionCompleto());
        lblFecha.setText(Parqueo.getInstance().getFactura().getFechaComplato());
        lblHorario.setText(Parqueo.getInstance().getFactura().getHorario());
        String n=String.valueOf(Parqueo.getInstance().getFactura().getNumFactura());
        lblNumFactura.setText(n);
        lblTelefono.setText(Parqueo.getInstance().getFactura().getMsjTelefono());
        */
        this.setVisible(rootPaneCheckingEnabled);
        this.setSize(1378, 766);
        initComponents();
        
        //String x= String.valueOf(Parqueo.getInstance().getUserCaja().calcularTarifa(Parqueo.getInstance().getVehiculo().getTiempoEstacionado()));
        //lblTotalNum.setText(x);
        
        
        
    }
    public static VentanaFactura getInstance(){
        if(VentanaFact == null)
            VentanaFact = new VentanaFactura();
        return VentanaFact;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCedulaJuridica = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblNumFactura = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalNum = new javax.swing.JLabel();
        lblPagacon = new javax.swing.JLabel();
        txtPagacon = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        bCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Parqueo ");

        lblHorario.setText("Abierto ");

        lblTelefono.setText("Tel: ");

        lblCedulaJuridica.setText("Cédula Jurídica: ");

        lblDireccion.setText("Dirección:  ");

        lblFecha.setText("Fecha: ");

        lblNumFactura.setText("Número Factura: ");

        lblTotal.setText("Total:");

        lblPagacon.setText("Paga con:");

        txtPagacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagaconActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        bCalcular.setText("Calcular");
        bCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecha)
                            .addComponent(lblDireccion)
                            .addComponent(lblCedulaJuridica)
                            .addComponent(lblHorario)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblTotal)
                                .addGap(56, 56, 56)
                                .addComponent(lblTotalNum)
                                .addGap(46, 46, 46)
                                .addComponent(lblPagacon)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelefono)
                                    .addComponent(lblNumFactura))
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPagacon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bCalcular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(btnAceptar)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorario)
                    .addComponent(lblTelefono))
                .addGap(31, 31, 31)
                .addComponent(lblCedulaJuridica)
                .addGap(27, 27, 27)
                .addComponent(lblDireccion)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(lblNumFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblTotalNum)
                    .addComponent(lblPagacon)
                    .addComponent(txtPagacon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar)
                    .addComponent(bCalcular))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPagaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagaconActionPerformed
        
    }//GEN-LAST:event_txtPagaconActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        int pago=Integer.parseInt(txtPagacon.getText());
        Parqueo.getInstance().getUserCaja().setPagoCliente(pago);
        
        String vuelto=String.valueOf(Parqueo.getInstance().getUserCaja().calcularVuelto());
        JOptionPane.showMessageDialog(null,"Su vuelto es de:"+vuelto+",gracias por su visita");
        
        Parqueo.getInstance().getHistorialFacturas()[Parqueo.getInstance().getFactura().getNumFactura()]=Parqueo.getInstance().getFactura();
        //System.out.print("Cobrito"+Parqueo.getInstance().getHistorialFacturas()[0].getCobro());
       // Parqueo.getInstance().getHistorialFacturas()
        this.hide();
        menu.getInstance().show();
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void bCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcularActionPerformed
        lblCedulaJuridica.setText("Cedula Juridica: "+Parqueo.getInstance().getFactura().getCedulaJuridica());
        
        lblDireccion.setText("Direccion: "+Parqueo.getInstance().getFactura().getDireccion());
        lblFecha.setText("Fecha: "+Parqueo.getInstance().getFactura().getFechaComplato());
        lblHorario.setText("Horario: "+Parqueo.getInstance().getFactura().getHorario());
        String numeroFact=String.valueOf(Parqueo.getInstance().getFactura().getNumFactura());
        lblNumFactura.setText("Numero de factura: "+numeroFact);
        lblTelefono.setText("Telefono: "+Parqueo.getInstance().getFactura().getNumTelefono());
        lblTitulo.setText("Titulo: "+Parqueo.getInstance().getFactura().getTitulo());
        
        //Parqueo.getInstance().getVehiculo().setTiempoEstacionado(Parqueo.getInstance().getVehiculo().getHoraSalida()-Parqueo.getInstance().getVehiculo().getHoraIngreso());
        //int i = Parqueo.getInstance().getFactura().getNumFactura();
        String cobro= Parqueo.getInstance().getFactura().getCobro();
        lblTotalNum.setText(cobro);
        
        this.repaint();
    }//GEN-LAST:event_bCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFactura().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCalcular;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel lblCedulaJuridica;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblNumFactura;
    private javax.swing.JLabel lblPagacon;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalNum;
    private javax.swing.JTextField txtPagacon;
    // End of variables declaration//GEN-END:variables
}
